version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-secure
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/config/certs
      